### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by decause** [JacobPlaster/ann-writer#1]
Firstly, thanks for sharing your code. I'm a huge fan of generative text libraries (particularly python libraries.) I was stoked to see your code, however, I didn't see a LICENSE or license headers in your repo. I may have missed it somewhere, but in case I didn't, I thought I would open an issue and encourage you to release under a FOSS license so that others can contribute back and build upon your excellent research :)

Happy Hacking,
--RemyD.

**Comment by JacobPlaster** [comment]
Thanks for the heads up! Completely forgot :)
